# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
 adapter: postgresql
 encoding: unicode

 pool: 5

development:
 <<: *default
 database: corpsb_development

test:
 <<: *default
 database: corpsb_test

production:
 <<: *default
 database: corpsb_production
 username: corpsb
 password: <%= ENV['CORPSB_DATABASE_PASSWORD'] %>

